[[redirects]]
from = "http://localhost:3000/"
to = "https://travel-log-eshan-naik.netlify.app/"
status = 301
force = false
[[redirects]]
from = "http://localhost:3000/main/signin"
to = "https://travel-log-eshan-naik.netlify.app/signin"
status = 301
force = false
[[redirects]]
from = "http://localhost:3000/main/signup"
to = "https://travel-log-eshan-naik.netlify.app/signup"
status = 301
force = false
[[redirects]]
from = "http://localhost:3000/main/forgot"
to = "https://travel-log-eshan-naik.netlify.app/forgot"
status = 301
force = false
[[redirects]]
from = "http://localhost:3000/main/add"
to = "https://travel-log-eshan-naik.netlify.app/add"
status = 301
force = false
[[redirects]]
from = "http://localhost:3000/main/remove"
to = "https://travel-log-eshan-naik.netlify.app/remove"
status = 301
force = false
[[redirects]]
from = "http://localhost:3000/main/view"
to = "https://travel-log-eshan-naik.netlify.app/view"
status = 301
force = false
[[redirects]]
from = "http://localhost:3000/main/aboutme"
to = "https://travel-log-eshan-naik.netlify.app/aboutme"
status = 301
force = false