export const ADD_LOG = 'ADD_LOG'
export const DELETE_LOG = 'DELETE_LOG'

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILED = 'REGISTER_FAILED';
export const LOGIN_FAILED = 'LOGIN_FAILED'; 
export const REMOVED_USER = 'REMOVED_USER';
export const REMOVED_USER_FAILED = 'REMOVED_USER_FAILED';

export const UPDATE_PASSWORD = 'UPDATE_PASSWORD';
export const UPDATE_PASSWORD_FAILED = 'UPDATE_PASSWORD_FAILED';